"use client";

import { Download, RefreshCw, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

import { HotspotGrid } from "@/components/intelligence/hotspot-grid";
import { TrendChart } from "@/components/intelligence/trend-chart";
import { StateBreakdown } from "@/components/intelligence/state-breakdown";

export default function IntelligenceReportPage() {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
  });

  return (
    <div className="flex flex-col gap-6 max-w-5xl mx-auto pb-10">
      {/* Report Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Intelligence Report</h1>
          <p className="text-muted-foreground mt-1">{currentDate}</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="gap-2">
            <RefreshCw className="h-4 w-4" /> Refresh
          </Button>
          <Button variant="outline" size="sm" className="gap-2">
            <Printer className="h-4 w-4" /> Print
          </Button>
          <Button size="sm" className="gap-2">
            <Download className="h-4 w-4" /> Export PDF
          </Button>
        </div>
      </div>

      {/* Executive Summary */}
      <Card>
        <CardHeader>
          <CardTitle>Executive Summary</CardTitle>
          <CardDescription>Automated threat assessment generated by AI models.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4 text-sm leading-relaxed">
          <p>
            Over the past 24 hours, the predictive analytics engine has detected a <strong>14% increase</strong> in 
            financial fraud indicators across targeted urban centers. The primary vector appears to be phishing 
            campaigns leveraging localized context. 
          </p>
          <p>
            Confidence scores for impending coordinated attacks in the Northern District remain high (89%), 
            warranting immediate preventive measures and resource allocation.
          </p>
        </CardContent>
      </Card>

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Primary Threat Trends</CardTitle>
          </CardHeader>
          <CardContent className="h-[300px]">
            <TrendChart />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>State-wise Breakdown</CardTitle>
          </CardHeader>
          <CardContent className="h-[300px]">
            <StateBreakdown />
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Identified Hotspots</CardTitle>
          <CardDescription>Regions with highest probability of incidents in the next 48 hours.</CardDescription>
        </CardHeader>
        <CardContent>
          <HotspotGrid />
        </CardContent>
      </Card>

      <Card className="border-l-4 border-l-primary">
        <CardHeader>
          <CardTitle>Actionable Recommendations</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="list-disc pl-5 space-y-2 text-sm">
            <li>Deploy digital awareness advisories targeting the financial sector in the Northern District.</li>
            <li>Increase monitoring frequency on localized communication channels.</li>
            <li>Coordinate with ISPs to block identified malicious domains associated with the ongoing phishing campaign.</li>
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}
