"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-10 17:12:17.670932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole'), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('withdrawal_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_type', sa.Enum('ATM', 'bank_branch', 'payment_kiosk', name='locationtype'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('atm_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('last_incident_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='chk_withdrawal_locations_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='chk_withdrawal_locations_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_withdrawal_locations_active_risk', 'withdrawal_locations', [sa.text('risk_score DESC')], unique=False, postgresql_where=sa.text('is_active = true AND risk_score >= 0.5'))
    op.create_index('ix_withdrawal_locations_is_active', 'withdrawal_locations', ['is_active'], unique=False)
    op.create_index('ix_withdrawal_locations_lat_lng', 'withdrawal_locations', ['latitude', 'longitude'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_number', sa.String(), nullable=False),
    sa.Column('victim_name_masked', sa.String(), nullable=True),
    sa.Column('victim_phone_masked', sa.String(), nullable=True),
    sa.Column('complaint_text', sa.String(), nullable=False),
    sa.Column('complaint_category', sa.Enum('vishing', 'phishing', 'otp_fraud', 'atm_fraud', 'other', name='complaintcategory'), nullable=True),
    sa.Column('amount_defrauded', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('complaint_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'predicted', 'resolved', name='complaintstatus'), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='chk_complaints_latitude'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='chk_complaints_longitude'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaints_bank_name', 'complaints', ['bank_name'], unique=False)
    op.create_index('ix_complaints_complaint_category', 'complaints', ['complaint_category'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_number'), 'complaints', ['complaint_number'], unique=True)
    op.create_index('ix_complaints_created_at', 'complaints', ['created_at'], unique=False)
    op.create_index('ix_complaints_lat_lng', 'complaints', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_complaints_state', 'complaints', ['state'], unique=False)
    op.create_index('ix_complaints_status', 'complaints', ['status'], unique=False)
    op.create_table('intelligence_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('alert_type', sa.Enum('hotspot_detected', 'pattern_change', 'high_risk_location', 'temporal_spike', name='alerttype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='alertpriority'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('affected_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intelligence_alerts_active_unack', 'intelligence_alerts', [sa.text('created_at DESC')], unique=False, postgresql_where=sa.text('is_active = true AND is_acknowledged = false'))
    op.create_index('ix_intelligence_alerts_affected_locations_gin', 'intelligence_alerts', ['affected_locations'], unique=False, postgresql_using='gin')
    op.create_index('ix_intelligence_alerts_created_at', 'intelligence_alerts', ['created_at'], unique=False)
    op.create_index('ix_intelligence_alerts_expires', 'intelligence_alerts', ['expires_at'], unique=False, postgresql_where=sa.text('is_active = true AND expires_at IS NOT NULL'))
    op.create_index('ix_intelligence_alerts_is_active', 'intelligence_alerts', ['is_active'], unique=False)
    op.create_index('ix_intelligence_alerts_priority', 'intelligence_alerts', ['priority'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('predicted_latitude', sa.Float(), nullable=False),
    sa.Column('predicted_longitude', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('predicted_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hotspot_cluster_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel'), nullable=True),
    sa.Column('prediction_radius_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('predicted_latitude BETWEEN -90 AND 90', name='chk_predictions_latitude'),
    sa.CheckConstraint('predicted_longitude BETWEEN -180 AND 180', name='chk_predictions_longitude'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_complaint_id', 'predictions', ['complaint_id'], unique=False)
    op.create_index('ix_predictions_created_at', 'predictions', ['created_at'], unique=False)
    op.create_index('ix_predictions_feature_importance_gin', 'predictions', ['feature_importance'], unique=False, postgresql_using='gin')
    op.create_index('ix_predictions_pred_lat_lng', 'predictions', ['predicted_latitude', 'predicted_longitude'], unique=False)
    op.create_index('ix_predictions_predicted_locations_gin', 'predictions', ['predicted_locations'], unique=False, postgresql_using='gin')
    op.create_index('ix_predictions_risk_level', 'predictions', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_risk_level', table_name='predictions')
    op.drop_index('ix_predictions_predicted_locations_gin', table_name='predictions', postgresql_using='gin')
    op.drop_index('ix_predictions_pred_lat_lng', table_name='predictions')
    op.drop_index('ix_predictions_feature_importance_gin', table_name='predictions', postgresql_using='gin')
    op.drop_index('ix_predictions_created_at', table_name='predictions')
    op.drop_index('ix_predictions_complaint_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_intelligence_alerts_priority', table_name='intelligence_alerts')
    op.drop_index('ix_intelligence_alerts_is_active', table_name='intelligence_alerts')
    op.drop_index('ix_intelligence_alerts_expires', table_name='intelligence_alerts', postgresql_where=sa.text('is_active = true AND expires_at IS NOT NULL'))
    op.drop_index('ix_intelligence_alerts_created_at', table_name='intelligence_alerts')
    op.drop_index('ix_intelligence_alerts_affected_locations_gin', table_name='intelligence_alerts', postgresql_using='gin')
    op.drop_index('ix_intelligence_alerts_active_unack', table_name='intelligence_alerts', postgresql_where=sa.text('is_active = true AND is_acknowledged = false'))
    op.drop_table('intelligence_alerts')
    op.drop_index('ix_complaints_status', table_name='complaints')
    op.drop_index('ix_complaints_state', table_name='complaints')
    op.drop_index('ix_complaints_lat_lng', table_name='complaints')
    op.drop_index('ix_complaints_created_at', table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_number'), table_name='complaints')
    op.drop_index('ix_complaints_complaint_category', table_name='complaints')
    op.drop_index('ix_complaints_bank_name', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('ix_withdrawal_locations_lat_lng', table_name='withdrawal_locations')
    op.drop_index('ix_withdrawal_locations_is_active', table_name='withdrawal_locations')
    op.drop_index('ix_withdrawal_locations_active_risk', table_name='withdrawal_locations', postgresql_where=sa.text('is_active = true AND risk_score >= 0.5'))
    op.drop_table('withdrawal_locations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table leaves the PG ENUM types behind, which
    # breaks a subsequent re-upgrade. Drop them explicitly.
    for enum_name in (
        "userrole",
        "locationtype",
        "complaintcategory",
        "complaintstatus",
        "alerttype",
        "alertpriority",
        "risklevel",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")